<!DOCTYPE html>
	<!--[if lt IE 7]>      <html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
	<!--[if IE 7]>         <html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
	<!--[if IE 8]>         <html lang="en" class="no-js lt-ie9"> <![endif]-->
	<!--[if gt IE 8]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Shift Block Explorer</title>
		<meta name="description" content="Block explorer for Shift SHF">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	</head>

	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<span class="icon-bar"></span><a href="/" class="navbar-brand">Shift Block Explorer</a>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<form action="/" name="search_form" class="navbar-form navbar-right" id="searchForm">
							<div class="form-group">
								<input type="text" placeholder="Tx Hash, Address or Block number" name="searchFor" required class="form-control">
							</div>
							<button type="submit" class="btn btn-success">Search</button>
						</form>
					</ul>
				</div>
			</div>
		</nav>

		<?=$this->data['layout_content']?>

		<footer>
			<hr>
			<p>
				© Shift 2016 |
				<a href="/api.php">API</a> |
				<a href="http://github.com/pharesim/shift_explorer">Fork me on GitHub</a>

			</p>
		</footer>

		<script src="https://code.jquery.com/jquery-2.2.2.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

	</body>
</html>